const FLAG_EMOJI: Record<string, string> = {
  NED: "🇳🇱",
  GBR: "🇬🇧",
  ESP: "🇪🇸",
  FRA: "🇫🇷",
  JPN: "🇯🇵",
  ITA: "🇮🇹",
  BRA: "🇧🇷",
  CAN: "🇨🇦",
  MEX: "🇲🇽",
  AUS: "🇦🇺",
  USA: "🇺🇸",
  FIN: "🇫🇮",
  CHN: "🇨🇳",
  DEU: "🇩🇪",
  DNK: "🇩🇰",
  CHE: "🇨🇭",
  AUT: "🇦🇹",
  MON: "🇲🇨",
  SWE: "🇸🇪",
  ARG: "🇦🇷",
  BEL: "🇧🇪",
  NZL: "🇳🇿",
  THA: "🇹🇭",
  POL: "🇵🇱",
  RUS: "🇷🇺",
  IRL: "🇮🇪",
  CZE: "🇨🇿",
  HUN: "🇭🇺",
  IND: "🇮🇳",
  INDONESIA: "🇮🇩",
  ZAF: "🇿🇦",
  KOR: "🇰🇷",
  VEN: "🇻🇪",
  COL: "🇨🇴",
  MYS: "🇲🇾",
  UAE: "🇦🇪",
  QAT: "🇶🇦",
  BHR: "🇧🇭",
  SAU: "🇸🇦",
  AZE: "🇦🇿",
  SGP: "🇸🇬",
  NLD: "🇳🇱",
  POR: "🇵🇹",
  EST: "🇪🇪",
  LVA: "🇱🇻",
};

export function countryFlagEmoji(
  code: string | null | undefined,
): string | null {
  if (!code) return null;
  return FLAG_EMOJI[code.toUpperCase()] ?? null;
}
